<?php
	// $Id$
/**
* Display help and module information
* @param path which path of the site we're displaying help
* @param arg array that holds the current path as would be returned from arg() function
* @return help text for the path
*/
function latestproject_help($path, $arg) {
	$output = '';  //declare your output variable
	switch ($path) {
	case "admin/help#latestproject":
	  $output = '<p>'.  t("Displays links to external Project") .'</p>';
	  break;
	}
	  return $output;
} // function onthisdate_help


function latestproject_theme() {
  return array(
    'forums' => array(
      'template' => 'latestproject',
      'arguments' => array('node' => NULL),
    ));
}
    
/**
* Valid permissions for this module
* @return array An array of valid permissions for the externalnews module
*/
function latestproject_perm() {
  return array('access latestproject content');
} // function onthisdate_perm()

/**
* Implementation of hook_block
* @param string $op one of "list", "view", "save" and "configure"
* @param integer $delta code to identify the block
* @param array $edit only for "save" operation
**/
function latestproject_block($op = 'list', $delta = 0, $edit = array()) {  
  if ($op == "list") {
    // Generate listing of blocks from this module, for the admin/block page
    $block = array();
    $block[0]["info"] = t('Latest Project');
    return $block;
  }else if ($op == 'view') {

   $limitnum = variable_get("latestproject_maxdisp", 3);    
   $result = array();
   
   $URL = 'http://cake.docuonline.com/project_byggfakta_tcis/projects/getprojects.xml';
  
   $ch = curl_init();
   curl_setopt($ch, CURLOPT_URL,$URL);
   curl_setopt($ch, CURLOPT_FAILONERROR,1);
   curl_setopt($ch, CURLOPT_FOLLOWLOCATION,1);
   curl_setopt($ch, CURLOPT_RETURNTRANSFER,1);
   curl_setopt($ch, CURLOPT_TIMEOUT, 5);
   $retValue = curl_exec($ch);
   curl_close($ch);
   if ($retValue != null) {
       if ( simplexml_load_string($retValue) ) {
           try{
                $oXML = new SimpleXMLElement($retValue);
            }
            catch (Exception $e ){
         
            }
       }
   }

   for ($i = 0; $i < count($oXML->projects) ; $i++ ) {
       $block_content .= ( $i == 0 ) ? "<div class='prosjektfakta' ><h3> Dagens prosjekter  </h3><ul>" : "";
       $block_content .= "<li>";
       $block_content .= $oXML->projects[$i]->create_date . '<br />';
       $block_content .='<strong>'. $oXML->projects[$i]->projectname. '</strong> <br />';
       $block_content .= $oXML->projects[$i]->address1. '<br />';
       $block_content .= $oXML->projects[$i]->geography2_name. '<br />';
       $block_content .= $oXML->projects[$i]->value. '<div class="linebreak-block"></div>';
       $block_content .= "</li>";
      $block_content .= ( $i == count($oXML->projects)-1 ) ? "</ul></div>" : "";
   }
   
  
    if ($block_content == '') {   
       $block['subject'] = 'Dagens prosjekter';
       $block['content'] = 'Sorry No Projects';
       return $block;
    }
    
    // set up the block
    $block['subject'] = 'Dagens prosjekter';
    $block['content'] = $block_content;
    return $block;
  } 
  
} 

function latestproject_admin() {
  $form = array();

  $form['latestproject_maxdisp'] = array(
    '#type' => 'textfield',
    '#title' => t('Maximum number of Projects'),
    '#default_value' => variable_get('latestproject_maxdisp', 3),
    '#size' => 2,
    '#maxlength' => 2,
    '#description' => t("The maximum number of projects to display in the block."),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

function latestproject_admin_validate($form, &$form_state) {
  $maxdisp = $form_state['values']['latestproject_maxdisp'];
  if (!is_numeric($maxdisp)) {
    form_set_error('latestproject_maxdisp', t('You must enter an integer for the maximum number of links.'));
  }
  else if ($maxdisp <= 0) {
    form_set_error('latestproject_maxdisp', t('Maximum number of projects must be positive.'));
  }
}

function latestproject_menu() {

  $items = array();

  $items['admin/settings/latestproject'] = array(
    'title' => 'Latest Project module settings',
    'description' => 'Description of your latest project settings page',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('latestproject_admin'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
   );

  return $items;
}

function template_preprocess_latestproject(&$node) {
 
}


